package constants

// STANDARD FONT CONSTANT
const BOLD = "B"
const REGULAR = ""
const ITALIC = "I"

const PRESC_DATA_FONT_SZ = 11

const PRESC_MED_FONT = "Mockine"
const PRESC_R_SLASH_FONT = "Jolly"
const PRESC_MED_QTY_UNIT_FONT = "Abuget"
const PRESC_MF_DOSE_FONT = "Pristina"
const PRESC_DET_FONT = PRESC_MED_QTY_UNIT_FONT

const PRESC_R_SLASH_FONT_SZ = 19
const PRESC_MED_FONT_SZ = 12
const PRESC_MED_QTY_UNIT_FONT_SZ = 16
const PRESC_DET_FONT_SZ = 21
const PRESC_MF_DOSE_FONT_SZ = 12

const ETIX_7X4_STD_FONT_SZ = 9

const INVOICE_STD_FONT_SZ = 8
const INVOICE_HEADER_FONT_SZ = 5
const INVOICE_TABLE_HEADER_FONT_SZ = 7
const INVOICE_TABLE_DATA_FONT_SZ = INVOICE_TABLE_HEADER_FONT_SZ - 1
const INVOICE_FOOTER_FONT_SZ = 9