package constants

// measurement in cm
const INVOICE_WIDTH = 10
const INVOICE_HEIGHT = 15
const INVOICE_MARGIN = 0.2
const INVOICE_STD_CELL_HEIGHT = 0.4
const INVOICE_FOOTER_CELL_HEIGHT = 0.5
const INVOICE_INFO_TITLE_WIDTH = 0.7

const INVOICE_HEADER_HEIGHT = 0.2

const INVOICE_TABLE_HEIGHT = 0.3
const INVOICE_NO_COL_WIDTH = 0.5
const INVOICE_ITEM_COL_WIDTH = 3.0
const INVOICE_QTY_COL_WIDTH = 0.9
const INVOICE_UNIT_COL_WIDTH = 0.8
const INVOICE_PRICE_COL_WIDTH = 1.8
const INVOICE_DISC_COL_WIDTH = 0.7
const INVOICE_SUBTOTAL_COL_WIDTH = 2.0

const INVOICE_STD_FONT_SZ = 8
const INVOICE_HEADER_FONT_SZ = 5
const INVOICE_TABLE_HEADER_FONT_SZ = 7
const INVOICE_TABLE_DATA_FONT_SZ = INVOICE_TABLE_HEADER_FONT_SZ - 1
const INVOICE_FOOTER_FONT_SZ = 9
