package constants

// measurement in cm
const POI_WIDTH = 21
const POI_HEIGHT = 14
const POI_MARGIN = 0.2

const POI_LOGO_WIDTH = 1.9
const POI_LOGO_HEIGHT = 1.9

const POI_STD_CELL_HEIGHT = 0.4
const POI_INFO_HEIGHT = 0.5

const POI_FOOTER_CELL_HEIGHT = 0.5

const POI_INFO_NUMBER_WIDTH = 1.7
const POI_INFO_DATE_WIDTH = 2.5
const POI_INFO_TERMS_WIDTH = 1.7
const POI_INFO_VENDOR_IS_TAX_WIDTH = 1.0
const POI_INFO_CASHIER_WIDTH = 1.7

const POI_HEADER_HEIGHT = 0.3
const POI_TABLE_HEIGHT = 0.6
const POI_NO_COL_WIDTH = 0.8
const POI_ITEM_COL_WIDTH = 12.5
const POI_QTY_COL_WIDTH = 2.5
const POI_UNIT_COL_WIDTH = 0

const POI_SUPPLIER_FONT_SZ = 9
const POI_STD_FONT_SZ = 11
const POI_HEADER_FONT_SZ = 8
const POI_TABLE_HEADER_FONT_SZ = POI_STD_FONT_SZ
const POI_TABLE_DATA_FONT_SZ = POI_TABLE_HEADER_FONT_SZ - 1