package constants

// measurement in cm
const PRESC_WIDTH = 10.8
const PRESC_HEIGHT = 21.3
const PRESC_MARGIN = 0.2
const PRESC_LOGO_WIDTH = 1.3
const PRESC_LOGO_HEIGHT = 1.3
const PRESC_STD_CELL_HEIGHT = 0.4

const PRESC_DATA_FONT_SZ = 11

const PRESC_MED_FONT = "Mockine"
const PRESC_R_SLASH_FONT = "Jolly"
const PRESC_MED_QTY_UNIT_FONT = "Abuget"
const PRESC_MF_DOSE_FONT = "Pristina"
const PRESC_DET_FONT = PRESC_MED_QTY_UNIT_FONT

const PRESC_R_SLASH_FONT_SZ = 19
const PRESC_MED_FONT_SZ = 12
const PRESC_MED_QTY_UNIT_FONT_SZ = 16
const PRESC_DET_FONT_SZ = 21
const PRESC_MF_DOSE_FONT_SZ = 12

const MAIN_DOCTOR = "JUSTUS KADIRMAN"