package constants

// measurement in cm
const PRODUCTION_WIDTH = 21
const PRODUCTION_HEIGHT = 14
const PRODUCTION_MARGIN = 0.2

const PRODUCTION_LOGO_WIDTH = 1.9
const PRODUCTION_LOGO_HEIGHT = 1.9

const PRODUCTION_STD_CELL_HEIGHT = 0.4
const PRODUCTION_INFO_HEIGHT = 0.5

const PRODUCTION_FOOTER_CELL_HEIGHT = 0.7

const PRODUCTION_HEADER_HEIGHT = 0.3
const PRODUCTION_TABLE_HEIGHT = 0.6

const PRODUCTION_NO_COL_WIDTH = 0.8
const PRODUCTION_BARCODE_COL_WIDTH = 4.0
const PRODUCTION_ITEM_COL_WIDTH = 8.5
const PRODUCTION_QTY_COL_WIDTH = 2.0
const PRODUCTION_UNIT_COL_WIDTH = 1.8
const PRODUCTION_COST_COL_WIDTH = 0

const PRODUCTION_STD_FONT_SZ = 11
const PRODUCTION_HEADER_FONT_SZ = 8
const PRODUCTION_TABLE_HEADER_FONT_SZ = PRODUCTION_STD_FONT_SZ
const PRODUCTION_TABLE_DATA_FONT_SZ = PRODUCTION_TABLE_HEADER_FONT_SZ - 1