package constants

const RECEIPT_WIDTH = PRESC_WIDTH
const RECEIPT_HEIGHT = PRESC_HEIGHT

const RECEIPT_MARGIN = 0.2
const RECEIPT_LOGO_WIDTH = 1.8
const RECEIPT_LOGO_HEIGHT = 1.8

const RECEIPT_CELL_HEIGHT_TITLE = 0.4
const RECEIPT_CELL_HEIGHT_BODY = 0.5

const RECEIPT_CELL_WIDTH_TITLE = 3.2

const RECEIPT_DATA_FONT_SZ = 12